services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: api_principal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  insurance-api:
    image: public.ecr.aws/i80/challenge-api
    ports:
      - "8080:5000"

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      HTTP_PORT:          ${HTTP_PORT}
      DATABASE_URL:       ${DATABASE_URL}
      INSURANCE_BASE_URL: ${INSURANCE_BASE_URL}
      INSURANCE_API_KEY:  ${INSURANCE_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      insurance-api:
        condition: service_started
